### ISSUE TITLE
Incorrect usage of settings storage

### ISSUE THREAD

**Issue by volodymyrdovhan** [jrangelardila/moodle-tool_copy_courses#4]
Hello,

the Moodle settings storage is not designed to store some temporary data, specifically large amounts of data.
Theoretically, users can upload CSV with hundreds of courses to clone, which will be inserted into 'config_plugins' DB table.

In addition, the unserialize() function is not secure, specifically when you try to save raw, uncleaned, not validated data from file to  DB table.

Please consider another approach to send data with POST request or to store the temp data in some temporary file.

Thank you.

![image](https://github.com/user-attachments/assets/5ec00e4b-cd38-4176-adc8-baabb3f83be4)
![image](https://github.com/user-attachments/assets/4f1686ae-4f67-4a1b-87b0-cd344c04a072)

**Comment by danmarsden** [comment]
yeah that's really the wrong place for this data - keep in mind that although it stores the data within the database, "config" is a special case and the data is actually stored inside a sites "cache" as well (for example in redis).  It's fine to store it in the database - just don't use the config table - store it in some other place instead - maybe it's own table?

I don't think this is something we'd block approval on, but keep in mind that this design may break a caching behavior in a site

**Comment by mudrd8mz** [comment]
I am generally not a fan of PHP's native unserialize() function and I try to avoid it whenever possible (incl. security reasons discussed at its manual page).

+1 to not block the approval on design decisions like this though, even if this really feels like an abuse of the plugin config tables.

**Comment by jrangelardila** [comment]
Hello
Thanks for their feedback.

I generated and aplicated the change
